### ISSUE TITLE
Warning: Undefined array key 1

### ISSUE THREAD

**Issue by herrweiss77** [pbd-kn/contao-inputvar-bundle#2]
Unter PHP 8.2 kommt im Debug-Modus eine Fehlermeldung:

```
Warning: Undefined array key 1
at vendor/pbd-kn/contao-inputvar-bundle/src/Resources/contao/Modules/InputVar.php:25
```

Nach dem ändern der entsprechenden Zeile auf 
`if ('' === ($arrTag[1] ?? '')) { ` 
konnte der Fehler behoben werden. 

Siehe: [https://contao.slack.com/archives/CK4J0KNDB/p1701794582736219](url)

**Comment by pbd-kn** [comment]
erledigt 1.0.22
